### ISSUE TITLE
Refactor: Implement Validator Messages

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#131]

**Comment by elpiel** [comment]
@samparsky you've mentioned that the RejectState timestamp should be the timestamp of the heartbeat/ApproveState, but since #140 was merged already and the [RejectState timestamp was left to `Utc::now()`](https://github.com/AdExNetwork/adex-validator-stack-rust/pull/140/files#diff-ef64eb8a6012169b260679340da9a460R137) I wanted to ping you and discuss if anything else is left on the Validator Messages.

**Comment by samparsky** [comment]
@elpiel I have created an issue to ensure that we fix it https://github.com/AdExNetwork/adex-validator-stack-rust/issues/149
