### ISSUE TITLE
Refactor: Fix RejectState timestamp

### ISSUE THREAD

**Issue by samparsky** [AdExNetwork/adex-validator-stack-rust#149]
RejectState timestamp should be the timestamp of the heartbeat/ApproveState,

**Comment by elpiel** [comment]
Can you provide a bit of information what should happen with this timestamp @samparsky ?

**Comment by samparsky** [comment]
I have updated the description of the issue

**Comment by elpiel** [comment]
Please give more information. There is no timestamp in the ApproveState.
Even in the JS implementation, only the heartbeat has.

**Comment by samparsky** [comment]
The timestamp field would be optional since not all validator messages have it

**Comment by elpiel** [comment]
Please refer to issue #101 as I think we have duplication.

**Comment by elpiel** [comment]
ping @samparsky

**Comment by samparsky** [comment]
Yeah it is closing this one
