### ISSUE TITLE
Database setup and migrations

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#151]
Database querying and etc:
- :negative_squared_cross_mark: `diesel` - excluded as an option as it's a synchronous ORM.
- :question: `bb8` - there is currently ongoing work to move to async/await and they are talking about (maybe) improving the API https://github.com/khuey/bb8/pull/37

Migration crates:
- https://github.com/jaemk/migrant_lib
- https://github.com/rust-db/barrel

**Comment by elpiel** [comment]
About the migrations:
- `Barrel` just spits out a query, which is not very useful for us.
- [`migrant`](https://github.com/jaemk/migrant) is a small CLI tool which just adds support for separate folders for up/down.sql files. It doesn't even support Transactions and we need to add the transactions ourselves.

For me there is no major benefit in using a migration tool for now, given the size and complexity of `sentry`.
cc @Ivshti @samparsky

**Comment by samparsky** [comment]
It's compulsory we have migrations i.e. it's not optional. 
I think migrant could work for us, having to write transaction queries isn't a problem.
Have you checked out https://github.com/jaemk/migrant_lib ?
