### ISSUE TITLE
Sentry logging

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#156]
We have many places which we log when something goes wrong. See the [JS implementation](https://github.com/AdExNetwork/adex-validator) for references where we need it.

Main questions we need to answer:
- What logger will be used
- What will be logged

Places we log in Sentry in the JS impl:
- [x] `Sentry listening on port X!` once sentry server is started #154 
- [x] `eventAggregator -> makeRecorder` insertion failed for `eventAggr` (`eventAggregator fatal error; will re-try`)

**Comment by samparsky** [comment]
slog works great, and whatever is logged in the JS implementation requires to be logged

**Comment by samparsky** [comment]
@elpiel Can we close this too?

**Comment by elpiel** [comment]
Do we want more places to log?
Can you also make sure we log the same thing in the `eventAggregate` since you are working on it?

**Comment by elpiel** [comment]
I think we have all the places we need to have logging, so I am closing this issue :tada: .
If there are any places we've missed or need to be added, we'll just use a new issue for that.
