### ISSUE TITLE
cfg: list_timeout is unused

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-rust#265]
should be used in the same way as the JS if it's easy enough

if not, it should be dropped

**Comment by samparsky** [comment]
list_timeout and fetch_timeout have the same values, so it's safe to say we can remove `list_timeout`

**Comment by elpiel** [comment]
Removed in https://github.com/AdExNetwork/adex-validator-stack-rust/commit/4ec4bb720f4df8ad647d71e1e75e9fc660174411
