### ISSUE TITLE
validatorWorker cmd args are incompatible with the JS version

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-rust#266]
Currently we have to provide all args as one-letter flags; It should be compatible with the JS version (e.g. `--sentryUrl=`)

**Comment by elpiel** [comment]
Hm... I think we've missed that we need to specify the [`.long()`](https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.long) name for the arguments.
Tbh I thought that `with_name()` should automatically specify it and we will only need to add the `.short()` one

Will do the fix asap!
