### ISSUE TITLE
GET /channel/:id/validator-messages without route parameters

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#338]
Double check if the Sentry route for `GET /channel/:id/validator-messages` is aligned with the JS implementation and allows to make a request without a `ValidatorId` & without Message `types` route parameters.

Check if routes are allowed:

* `/channel/0x.../validator-messages`
* `/channel/0x.../validator-messages/0x....`
* `/channel/0x.../validator-messages/0x..../NewState+....`

**Comment by simzzz** [comment]
All 3 sentry routes are working and return accurate output, including validatorMessages.
