### ISSUE TITLE
figure out what to do with Futures going forward

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-rust#4]
using futures 0.1 and 0.3 in the same codebase does not have any performance penalties, but it has significant code quality penalties

we have to pick one of the following:

- use a tokio alternative built on futures 0.3: https://github.com/withoutboats/romio
- use futures 0.1 exclusively
- structure the code in a way that only 2 distinct parts use futures 0.1: the tokio server boilerplate, and a postgres wrapper; everything else should be async/await (futures 0.3)

I'm in favour of the third

**Comment by elpiel** [comment]
Since Sentry is now disabled and will be redone at some point, we can migrate the rest of the crates to the latest nightly and `.await` syntax
