### ISSUE TITLE
AIP #61 v5:  GET (list) Campaigns

### ISSUE THREAD

**Issue by simzzz** [AdExNetwork/adex-validator-stack-rust#429]
Part of #382 
- Separate table for channels and campaigns, one-to-many relation with `channel_id`

- Query params:
  - `validator` - Address
  - `leader` - Address:

- [x] Changes to Query params https://github.com/AdExNetwork/adex-validator-stack-rust/pull/445

**Comment by elpiel** [comment]
- [x] Add Pagination
