### ISSUE TITLE
Replace relayer with Identity.isValidSignature in Ethereum adapter

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#452]
In V5 with new Identity contract we should not call relayer anymore instead we should use the Identity contract's `isValidSignature`.

- [x] Create a test using `Payload.identity` for authentication
-  ~Update Snapshot to include `Identity` contract (see #403)~ Not needed, we can deploy the identity when needed.

Pseudo code old:
```
const signer = ecrecover(hash(token)) // whoever signed the message
if (isIdenity) return getPrivilegesFromRelayer(identityAddr)[signer] ? identityAddr : null
else return signer
```

Pseudo code new:
```
const signer = ecrecover(hash(token)) // whoever signed the message
if (isIdentity) return new Identity(identityAddr).isValidSignature(sig) ? identityAddr : null
else return signer
```

**Comment by Ivshti** [comment]
@elpiel Correct, we an just use a signature for the EIP 1271 spec and verify this with `isValidSignature`
