### ISSUE TITLE
Sentry REST API documentation

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-validator-stack-rust#475]
We need a way to easily document the REST API of sentry in using `rustdoc`.
Two ideas come to mind:
- ~Doc macro for serialization inside the doc comments~ - It's more difficult than expected, this is put on hold
- Building json/queries example files using Rust and include them inside the docs

## Doc macro for serialization (on hold)

We need to serialize to json & urlencode fir structs inside doc comments.

A similar macros to https://github.com/scrabsha/dep-doc with arguments of rust structs and expression:
`let my_struct = MyStruct { field: .. }`

with the following variants:

- `doc_urlencode!` - urlencode the struct and print it in docs
- `doc_json!` - pretty-print the struct in json format inside the docs

# Building docs

We now build docs based on `aip-61-adex-v5` branch with default path to `sentry` crate and we deploy it with GH pages at:

https://ambiretech.github.io/adex-validator-stack-rust

**Comment by elpiel** [comment]
I've posted a question on the Rust user forum to see if it's even possible to capture the scope of the doc test and use variables inside it to generate JSON examples:

https://users.rust-lang.org/t/macro-invocation-in-rustdoc-and-generating-examples/74759

**Comment by simzzz** [comment]
### Remaining tasks:

##### GET `/v5/channel/:id/accounting`
- [x]   More thorough documentation
- [x] Examples for `AccountingResponse::<CheckedState>`

##### GET `/v5/channel/:id/spender/:addr` (auth required)
- [x] 	More thorough documentation
- [x]  Examples for `SpenderResponse`

##### GET `/v5/channel/:id/spender/all` (auth required)
- [x] 	More thorough documentation
- [x] 	Examples for `AllSpendersResponse`

##### GET `/v5/channel/:id/validator-messages` @elpiel #534 
- [x] 	Examples for `ValidatorMessagesListQuery` 
- [x] 	Examples for `ValidatorMessagesListResponse`  

##### POST `/v5/channel/:id/validator-messages` (auth required) @elpiel #534 
- [x] 	More thorough documentation
- [x] 	Examples for `ValidatorMessagesCreateRequest`

##### GET `/v5/channel/:id/last-approved` @elpiel #534 
- [x]  More thorough documentation
- [x] 	Examples for `LastApprovedQuery`
- [x] 	Examples for `LastApprovedResponse`

##### POST `/v5/channel/:id/pay` (auth required)
- [x] Examples for `ChannelPayRequest`

##### GET `/v5/channel/:id/get-leaf`
- [x] Response examples

##### POST `/v5/channel/dummy-deposit` (auth required) @elpiel #534 
- [x] 	Examples for ChannelDummyDeposit

##### Other

- [ ] GET `/cfg` @simzzz #545
